### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by matusrajnoha** [tombolano/goodwe-sec1000-info#1]
How to install this? Or how to use? Git repository url is not valid...

**Comment by tombolano** [comment]
Hello, the readme explains how to run the code, you can run the python script [goodwe_sec1000_info.py](https://github.com/tombolano/goodwe-sec1000-info/blob/master/goodwe_sec1000_info.py) directly or import it into another script (see [goodwe_sec1000_info_test.py](https://github.com/tombolano/goodwe-sec1000-info/blob/master/goodwe_sec1000_info_test.py) for an example). What do you mean by "Git repository url is not valid"?

**Comment by matusrajnoha** [comment]
Sorry, but I have no idea how and where to run that code. We are willing to pay you if you help us get it up and running. We have a Goodwe 60kW with SEC1000 and I can't regulate it.

 

Od: Tomás Domínguez Bolaño ***@***.***>
Príjemca odpovede: tombolano/goodwe-sec1000-info ***@***.***>
Dátum: pondelok, 10. októbra 2022, 14:24
Komu: tombolano/goodwe-sec1000-info ***@***.***>
Kópia: Matus Rajnoha ***@***.***>, Author ***@***.***>
Predmet: Re: [tombolano/goodwe-sec1000-info] How to install this? (Issue #1)

 

Hello, the readme explains how to run the code, you can run the python script goodwe_sec1000_info.py directly or import it into another script (see goodwe_sec1000_info_test.py for an example). What do you mean by "Git repository url is not valid"?

**Comment by tombolano** [comment]
Sorry, the code in this repository does not allow to configure the SEC1000, it only allows to recover the realtime data. To configure the SEC1000 you may try to use the ProMate software provided by GoodWe, this is the link to the software from the spanish GoodWe website: https://es.goodwe.com/images/download/GW_Ezlogger%20Pro%20ProMate.rar. Also be sure to check the manual: https://en.goodwe.com/Ftp/EN/Downloads/User%20Manual/GW_SEC1000S_User%20Manual-EN.pdf

Also I actually don't know how to configure the SEC1000, my work with the SEC1000 only involved obtaining the realtime data, the configuration was done by other people. 

This is a screenshot of the software from the SEC1000 manual:
<img src="https://user-images.githubusercontent.com/86369321/194910070-ae4dede6-a2ba-4c53-88ba-1206010d5aa7.png" width=75%>

The code in this repository only allows to recover the data that is shown in the tab labeled "realtime data", if you are interested in obtaining this data with this code you need to install the python interpreter and run the code with it.
