### ISSUE TITLE
Strange values for P1/P2/p3

### ISSUE THREAD

**Issue by elxsi** [tombolano/goodwe-sec1000-info#3]
Hi,

current setup:

- SEC1000S with 200A (pri) / 5A (sec) current trackers
- CT ratio is set to 40 (200A / 5A = 40)
- 2 x GoodWe ET Plus+ Hybrid GW 8 K-ET inverters
- No battery / BMS

I'm experiencing some strange values for P1/P2/P3. If I understand this correctly:

- positive values for P1/P2/P3 mean power is delivered to mains (sell)
- negative values for P1/P2/P3 mean power is consumed from mains (buy)

So I've constantly queried the SEC1000s for the corresponding values (one query per minute), and I found something strange. During the night, when all inverters are off ("waiting mode"), I always have negative values for P1 and P2 (power is consumed from mains) but positive values for P3 (power is delivered to mains):

`
{
    "v1": 224.60000000000002,
    "v2": 224.60000000000002,
    "v3": 224.70000000000002,
    "i1": 2.82,
    "i2": 3.5300000000000002,
    "i3": 3.83,
    "p1": -0.308,
    "p2": -0.34400000000000003,
    "p3": 0.497,
    "meters_power": -0.155,
    "inverters_power": 0.001
}
`

Or with the test script:

`
Total number of bytes received: 56

Bytes:
b'\x04REVO\x001\x01\x01\x0b\x00\x00\x08\xbe\x00\x00\x08\xc9\x00\x00\x08\xd2\x00\x00\x00\xfb\x00\x00\x01B\x00\x00\x01i\xff\xff\xff(\xff\xff\xfe\xf2\x00\x00\x01\xc7\xff\xff\xff\xe1\x00\x00\x00\x03\x0f\xe2'

Fields:
045245564F00 	 Header: \x04REV0\x00
31 		 Data lenght: 49
01010B 		 Unknown (request code?)
000008BE 	 Voltage 1 (0.1V units): 2238
000008C9 	 Voltage 2 (0.1V units): 2249
000008D2 	 Voltage 3 (0.1V units): 2258
000000FB 	 Current 1 (0.01A units): 251
00000142 	 Current 2 (0.01A units): 322
00000169 	 Current 3 (0.01A units): 361
FFFFFF28 	 Power 1 (1W units): -216
FFFFFEF2 	 Power 2 (1W units): -270
000001C7 	 Power 3 (1W units): 455
FFFFFFE1 	 Meter power (1W units): -31
00000003 	 Inverters power (1W units): 3
0FE2 		 Data checksum, calculated = FE2
`

The absolute values of P1/P2/P3 seem to be correct though. I've also checked the direction of the three CTs and all of them or correctly placed. Any ideas what is going on here?

Thank you :)

**Comment by tombolano** [comment]
It is strange, from the data that you show it looks like it might be some hardware problem, but unfortunately I don't know what could be wrong there. I actually have no experience with these kinds of electrical installations, the code in this repository was made for an already existing solar power system, and I only took care of making this code for retrieving the data, I don't know much more.

I would suggest asking on the goodwe community forum: https://community.goodwe.com/Forum
There is also other forums devoted to solar power systems where could try asking such as https://diysolarforum.com/, https://powerforum.co.za, or https://forum.buildhub.org.uk/forum/121-photovoltaics-pv/
